# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  fiziks_config = debug
endif

PROJECTS := fiziks

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

fiziks:
ifneq (,$(fiziks_config))
	@echo "==== Building fiziks ($(fiziks_config)) ===="
	@${MAKE} --no-print-directory -C . -f fiziks.make config=$(fiziks_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f fiziks.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   fiziks"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"